pair programming
X-Elie-X/X-Elie-X.github.io pull request #5
Opened 2022-07-20 09:21 UTC by X-Elie-X

## In this PR I implemented the below:

- Creating a new repository.
- Upload all my portfolio files.
- we Created a popup window.
- Add main.js to activate the buttons and show the `popup` effects.
- Add some style for the `popup` design

2022-07-20 10:47 UTC, codecaiine requested changes
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
No linters errors :heavy_check_mark: 
Good pull request description :heavy_check_mark: 

## Required Changes ♻️

- [x] Good job so far but Please [Check the project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md) because some requirements are not implemented well :+1: 
- [ ] I would like to recommend you to work on your mobile version because it s not working as expected , you need to give to your user a good experience :+1: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 10:47 UTC, codecaiine commented on main.js
> +// }
- [ ] I would like to recommend you remove all the commented code from your codebase in order to keep your code clean :smile:

2022-07-20 10:47 UTC, codecaiine commented on main.js
> +const listInfo = document.getElementById('listinfo');
- [ ] Please create an array of objects to store JavaScript objects containing the information for each project in your JavaScript file :+1: 

- [ ] Make sure that your project object contains information about the project: `name`, `description`, `image`, `technologies`, `links to live version`, and `link to the project source code`.
you should have something like that: 
```javascript
const projects = [{
    name: "project name",
    description: "Build portfolio popup window",
    image: "link_to_image",
    technologies: ["html", "JavaScript", "Css"],
    link: "link_to_live_version.com",
}]
```

2022-07-20 10:47 UTC, codecaiine commented on index.html
> +    </section>
- [ ] Please ensure that your projects section is created dynamically with the information from the projects array you created in your Javascript file :+1:  

- [ ] Please make sure that your modal popup data is populated with the data from the project's array :smile:

2022-07-20 10:47 UTC, codecaiine commented on index.html
> +    <section class="popup" id="popup1">
- [ ] Good job so far your popup is displaying :+1: But it is not working as expected :cry:  For Desktop your popup does not conform to the dimensions set in the Figma template. You can see a difference when you compare it to Figma. Please use the dimensions and follow the layout as defined in the Figma template to make them similar. :smile: 

### Figma template
![Screenshot from 2022-07-20 09-53-21](https://user-images.githubusercontent.com/6615394/179960135-152c5666-d27e-4b77-9f41-f0082fc057ea.png)

### Your project
![Screenshot from 2022-07-20 09-51-46](https://user-images.githubusercontent.com/6615394/179960142-631b545d-cf91-4643-9909-0a85856d532f.png)




- [ ] For the Mobile version the details about the project do not appear. The elements are improperly placed as you can see in the picture below :disappointed: Please fix it so they can appear on the popup so it looks similar to the Figma template. :+1: 

### Figma template
![Screenshot from 2022-07-20 10-31-46](https://user-images.githubusercontent.com/6615394/179961954-bdb7cfcf-d11e-466e-b592-4ede70a06db1.png)

### Your work
![Screenshot from 2022-07-20 09-54-24](https://user-images.githubusercontent.com/6615394/179960129-b21950e6-5ef4-4cb1-ad81-cf9825f32796.png)

2022-07-20 10:47 UTC, codecaiine commented on index.html
> +      <button type="button" class="close-popup" id="close-popup">X</button>
- [ ] We can not click or tap the **close (X) button,** and the popup disappear. :disappointed:   Please fix it to give your user a great user experience :smile:

2022-07-21 14:57 UTC, ishimwezachee approved these changes
Hi @X-Elie-X , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/DhstvI3zZ598Nb1rFf/giphy-downsized-medium.gif"/>
## Highlights
Linters are passing 👍 
The project is running successfully 👍 
PR is well described 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 15:00 UTC, merged